apiVersion: v1
entries:
  grafana:
    - apiVersion: v2
      appVersion: 8.4.6
      created: "2022-05-10T18:33:07.564886052+05:30"
      description: The leading tool for querying and visualizing time series and metrics.
      digest: 6703066693b9f077b5422c3eab25465913a0b466fba897aed9b0b9dffe6a164b
      home: https://grafana.net
      icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
      kubeVersion: ^1.8.0-0
      maintainers:
        - email: zanhsieh@gmail.com
          name: zanhsieh
        - email: rluckie@cisco.com
          name: rtluckie
        - email: maor.friedman@redhat.com
          name: maorfr
        - email: miroslav.hadzhiev@gmail.com
          name: Xtigyro
        - email: mail@torstenwalter.de
          name: torstenwalter
      name: grafana
      sources:
        - https://github.com/grafana/grafana
      type: application
      urls:
        - https://vijeyash1.github.io/grafana-chart/grafana-6.26.7.tgz
      version: 6.26.9
generated: "2022-05-10T18:33:07.562702028+05:30"
